# NumPy : Introduction

**NumPy allows you to manipulate data in the form of an array.**

**Complete the missions below using NumPy.**

In [ ]:

import numpy as np # Here we rename numpy as np, it's shorter, and everybody does that

# Mission 1 : Display the version of NumPy you are running

print(np.__version__)


1.19.5


In [ ]:
# Mission 2 : Create a NumPy array with a length of 3, that contains this 3 floats: 0.8, 0.6, 0.4
# Expected result: array([0.8, 0.6, 0.4])

array10 = np.array([0.8, 0.6, 0.4])
array10


array([0.8, 0.6, 0.4])

In [ ]:
# Mission 3 : Create a function that uses the np.random.random() function to return an array with 10 random elements, 
# all of which must be greater than 0.25 and less than 1.0

# Example of expected result: array([0.3897948 , 0.82850041, 0.5499838 , 0.81940137, 0.92175875, 0.89634373, 0.26821861, 0.72376496, 1.21098623, 0.28192741])

def my_Function():
  array1 = []
  for i in range (10):
    a = np.random.random()
    while a < 0.25:
      a = np.random.random()
    array1.append(a)

  return np.array(array1)

my_Function()




array([0.94397848, 0.51152668, 0.87265096, 0.56655145, 0.78858836,
       0.60260977, 0.80819691, 0.68201896, 0.88895304, 0.79517181])

In [ ]:
# Mission 4 : What does the np.empty() method do? Don't just copy the documentation, explain in your own words here

#As seen bellow np.empty creates an array of the desired sized containing arbitrary values
array11 = np.empty(10) 
print (array11)
print ("-----------------------------------")
#it can also be used to create an array of a specific shape and datatype
array13 = np.empty(shape = [3, 5], dtype = str)
array13

#The "empty" part means that the value returned are empty of any meaning

[4.6311521 4.6311521 4.6311521 4.6311521 4.6311521 4.6311521 4.6311521
 4.6311521 4.6311521 4.6311521]
-----------------------------------


array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [ ]:
# Mission 5 : Create an array filled with only zeros. You can chose the length of this array.
array15 = np.zeros(10)
array15

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Mission 6 : Create an array filled with 10 random integers.

array16 = np.random.randint(10, size=10)
array16


array([7, 4, 0, 2, 9, 8, 1, 7, 6, 7])

In [ ]:
# Mission 7 : Create an array that contains 50 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.

array17 = np.random.randint(8, size=50)
array17

array([2, 3, 2, 2, 7, 3, 7, 4, 7, 3, 7, 4, 4, 0, 5, 0, 4, 4, 5, 4, 2, 4,
       1, 3, 1, 2, 0, 2, 0, 5, 2, 4, 0, 7, 0, 3, 0, 2, 5, 5, 3, 1, 4, 7,
       3, 0, 5, 0, 7, 7])

In [ ]:
# Mission 8 : Use the slicing operator to return the items between position 3 and 6 inclusive, from the array in mission 6

array16[2:6:]

array([2, 9, 8, 1])

In [ ]:
# Mission 9 : Use the `argmin()` method to return the index of the smallest element in the array from mission 6

np.argmin(array16)

2

In [ ]:
# Mission 10 : Using the `where()` method, return the indices of all the values in the array from mission 6 that are greater than their median value.

np.where(array16 > np.mean(array16))

(array([0, 4, 5, 7, 8, 9]),)

In [ ]:
# Mission 11: Create 3 arrays filled with 5 random integers each, and place them in another array.
# You have now an array with (3, 5) shape. You can use the `shape` attribute to check it.
# Display the elements, with each column appearing on a different line (so there will be 5 lines with 3 values each)

array18 = np.random.randint(10, size = 5)
array19 = np.random.randint(10, size = 5)
array20 = np.random.randint(10, size = 5)

array21 = np.vstack([array18, array19, array20])
print (array21)

print ("--------------------------")

emptyarry = np.empty([5,3], int)

print (array21.transpose())






[[9 6 5 3 6]
 [1 6 1 1 3]
 [8 3 8 7 8]]
--------------------------
[[9 1 8]
 [6 6 3]
 [5 1 8]
 [3 1 7]
 [6 3 8]]


In [ ]:
# Mission 12: Create an array and fill it with 20 random float values.
# Create a function that returns the smallest and largest value it contains, with their indexes!
# You are allowed to use `min()` and `max()` methods.
# Example with a shorter array: [300, 500, 1000, 700, 100, 600] -> (4, 100), (2, 1000)
# Example with a shorter array: [80, 50, 90, -20, 100, 10] -> (3, -20), (4, 100)

array22 = np.random.random(20)
minValue = min(array22)
maxValue = max(array22)

index_Min_Value = np.argmin(array22)
index_Max_Value = np.argmax(array22)
print (array22)
print (minValue, index_Min_Value)
print (maxValue, index_Max_Value)



[0.93933253 0.24305042 0.96199141 0.66623894 0.2003977  0.23681814
 0.12956292 0.1338984  0.75209644 0.90754864 0.62590662 0.73449262
 0.860038   0.22522831 0.64912425 0.86725159 0.88278931 0.38801116
 0.35696843 0.06390642]
0.063906421762296 19
0.9619914136678878 2


In [ ]:
# Mission 13: Create 2 arrays, randomly fill them with 20 int values between 0 and 10.
# Create a function that will go through each array using a for loop.
# At each iteration of the loop the function should compare the values of the 2 arrays located at the same index position.
# Return all indices where the values of the 2 arrays happen to be equal, in a list.
# If no values are equal at the same indices across the 2 arrays, that list will be empty.
# Example with shorter arrays: [1, 3, 5, 7] & [2, 3, 5, 8] -> [1, 2]
# Example with shorter arrays: [1, 1, 1, 1] & [1, 2, 3, 4] -> [0]

array23 = np.random.randint(10, size = 20)
array24 = np.random.randint(10, size = 20)
print (array23)
print (array24)

def new_my_function():
  newList = []
  for i in range (array23.shape[0]):
    if array23[i] == array24[i]:
      newList.append(i)
  return newList

new_my_function()



[6 2 4 1 1 0 1 8 5 6 3 3 8 4 6 9 8 0 6 9]
[4 4 9 3 0 0 4 6 9 3 4 4 9 0 3 7 1 3 1 6]


[5]

In [ ]:
# Mission 14: now, just compare both arrays of mission 13 with this command (change the name of arrays): array1 == array2

array23 == array24

array([False, False, False, False, False,  True, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False])