# Mission 1

Find a way to calculate the following statistical indicators for any given one-dimensional array using NumPy functions, and use them on a array filled with 20 random floats.
- mode
- median
- average
- the range (the difference between max and min)
- standard deviation
- variance
- the different quantiles

Then, create another array with 20 random floats and calculate the Pearson coefficient between the two arrays.

In [ ]:
import numpy as np

array22 = np.random.random(20)
print (array22, "\n")

value, count = np.unique(array22, return_counts= True)

print (f"Mode: {value[np.argmax(count)]}")
print (f"Median: {np.median(array22)}")
print (f"Average: {np.mean(array22)}")
max1 = np.amax(array22)
min1 = np.amin(array22)
print (f"Range: {max1 - min1}")
print (f"Standard deviation: {np.std(array22)}")
print (f"Variance: {np.var(array22)}")
print (f"Quartile 1: {np.quantile(array22, 0.25)}")
print (f"Quartile 2: {np.quantile(array22, 0.5)}")
print (f"Quartile 3: {np.quantile(array22, 0.75)}")
print (f"Quartile 4: {np.quantile(array22, 1)}")
print ("\n")

array23 = np.random.random(20)
print (array23, "\n")

print (np.corrcoef(array22, array23))


[0.18399424 0.35388538 0.58806667 0.43195806 0.54138354 0.66747497
 0.15839055 0.54409682 0.5509797  0.83981729 0.72602379 0.27026418
 0.65050654 0.95573477 0.62211292 0.3310368  0.49075093 0.64499082
 0.753649   0.92068785] 

Mode: 0.15839055395066792
Median: 0.5695231866064002
Average: 0.5612902411198472
Range: 0.7973442133768815
Standard deviation: 0.2196630614556285
Variance: 0.048251860568059225
Quartile 1: 0.41243988992782044
Quartile 2: 0.5695231866064002
Quartile 3: 0.6821121781287699
Quartile 4: 0.9557347673275495


[0.28544268 0.87166043 0.19149719 0.25233414 0.35911506 0.57679836
 0.43789493 0.83100605 0.38931486 0.95641946 0.53235428 0.78641541
 0.67215462 0.65885826 0.29959929 0.23036427 0.1384071  0.30403969
 0.26149006 0.22139494] 

[[1.         0.09113544]
 [0.09113544 1.        ]]


## Mission 2

Create a function using NumPy that indicates the values (integers only), from -100 to 100, where the remainder from performing Euclidean division by both 3 and 7 is equal.

In [ ]:
def myfunctionarr():
  newList = []
  for i in range (-100, 101, 1):
    if np.remainder(i, 3) == np.remainder(i, 7):
      newList.append(i)
  return newList

myfunctionarr()

[-84,
 -83,
 -82,
 -63,
 -62,
 -61,
 -42,
 -41,
 -40,
 -21,
 -20,
 -19,
 0,
 1,
 2,
 21,
 22,
 23,
 42,
 43,
 44,
 63,
 64,
 65,
 84,
 85,
 86]

## Mission 3

Create a function that returns the [inverse value (for `3`, return `1/3`)](https://en.wikipedia.org/wiki/Multiplicative_inverse) of a set of values contained in a NumPy array

In [ ]:
array21 = np.random.randint(1, 10, size = 20)
print (array21)

def anotherNewFunction():
  return 1/array21

anotherNewFunction()


[4 6 7 3 5 2 1 5 2 9 3 9 7 5 9 5 9 3 6 6]


array([0.25      , 0.16666667, 0.14285714, 0.33333333, 0.2       ,
       0.5       , 1.        , 0.2       , 0.5       , 0.11111111,
       0.33333333, 0.11111111, 0.14285714, 0.2       , 0.11111111,
       0.2       , 0.11111111, 0.33333333, 0.16666667, 0.16666667])